name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build:prod

      - name: Lint (ts, scss)
        run: |
          npm run lint:ts
          npm run lint:scss

      - name: Test
        run: npm run test:unit

      - name: Test (UI)
        run: |
          npm run storybook:build
          npm run test:ui:ci
